name: Build

on:
  workflow_dispatch: ~
  push:
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'pom.xml'
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'pom.xml'
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout Arcturus Morningstar
      uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    # Remove SNAPSHOT when building a tag.
    - name: Build Arcturus Morningstar
      run: |
        if [[ $GITHUB_REF_TYPE == 'tag' ]]; then
          mvn -B package -DcommitHash=${GITHUB_SHA} -Dchangelist=
        else
          mvn -B package -DcommitHash=${GITHUB_SHA}
        fi

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: Arcturus Morningstar
        path: target/*.jar
